### ISSUE TITLE
Backup/Restore only certain apps

### ISSUE THREAD

**Issue by PescheHelfer** [marcmerlin/android-adb-backup#1]
Thanks for creating this project! The readme is not quite clear about whether it is also possible to backup/restore individual apps, and if so, how it would be done. 

Thanks and best regards

**Comment by marcmerlin** [comment]
Sure, https://github.com/marcmerlin/android-adb-backup/blob/master/restore_apps.sh takes a list of apps to restore by name
https://github.com/marcmerlin/android-adb-backup/blob/master/backup_apps.sh backs up all the apps.

Note that these scripts are not super foolproof, they may require you to read them and adjust them a bit for your need, but hopefully they should work out of the box or with minor changes.
But let's be clear that you need an android build that has root. If "adb root" does not work for you, you can't use this code.
In that case, you're stuck with the built in android backups, which have gotten somewhat better recently.
Good luck

**Comment by PescheHelfer** [comment]
Oh, seems I missed the root part :( Thanks for the info, anyway!
